### ISSUE TITLE
求助，打开exe程序后显示无法找到配置文件？

### ISSUE THREAD

**Issue by psychopath020** [HengXin666/BiLiBiLi_DanMu_Crawling#1]
已将ini文件放在了和exe同一文件夹内，但仍显示【找不到文件 HX配置文件.ini】，大佬求助已将ini文件放在了和exe同一文件夹内，但仍显示【找不到文件 HX配置文件.ini】，大佬求助

**Comment by HengXin666** [comment]
下载 .exe 文件 需连 .ini 文件一起下载,下载后要将.ini 文件重命名为 [ HX配置文件.ini ] (github不支持上传包含中文的)
