### ISSUE TITLE
请求 | 自己填写cid

### ISSUE THREAD

**Issue by daminoac** [HengXin666/BiLiBiLi_DanMu_Crawling#3]
我想要爬取av10492的弹幕，但是现在这个视频已经失效，因此软件无法获取到cid，我用其他方法获取到了cid，发现无法自己填写，求支持自己填写cid

**Comment by HengXin666** [comment]
您好，我个人认为这不是一个必要的功能 (因为平常的获取方法只有这一个)

而且, **因为如果视频已经失效的话, 即便知道cid, 也`无法`获取到历史弹幕的**

如果您真的需要尝试一下的话，可以在配置文件中设置:

(配置文件在: `./config/config.json`)

```json
{
    "settings": {
        "cid": 66926, // 此处填写您需要爬取视频的cid, 然后打开程序 (不要在运行的时候修改, 因为会被覆盖)
        "startDate": "2013-09-17",
        "endDate": "2024-11-02",
        "isGetAllDanmMaKu": true,
        "isGetToNowTime": true
    },
    // ...
}
```

> 感谢您的支持, 但是我也十分抱歉qwq

**Comment by daminoac** [comment]
> 您好，我个人认为这不是一个必要的功能 (因为平常的获取方法只有这一个)
> 
> 而且， **因为如果视频已经失效的话， 即便知道cid， 也获取到历史弹幕的**
> 
> 如果您真的需要尝试一下的话，可以在配置文件中设置:
> 
> (配置文件在:`./config/config.json`)
> 
> ```json
> {
>     "settings": {
>         "cid": 66926, // 此处填写您需要爬取视频的cid, 然后打开程序 (不要在运行的时候修改, 因为会被覆盖)
>         "startDate": "2013-09-17",
>         "endDate": "2024-11-02",
>         "isGetAllDanmMaKu": true,
>         "isGetToNowTime": true
>     },
>     // ...
> }
> ```
> 
> > 感谢您的支持， 但是我也十分抱歉qwq;希望对您有帮助
