### ISSUE TITLE
爬取日期从2009-01-01开始

### ISSUE THREAD

**Issue by zishu0802** [HengXin666/BiLiBiLi_DanMu_Crawling#5]
设定的爬取日期不管用
<img width="365" alt="image" src="https://github.com/user-attachments/assets/4e48baa8-773c-4e14-ae33-5c235fe2c7db">

**Comment by HengXin666** [comment]
您好，非常抱歉, 这确实是一个bug, 我现在立即去修复一下(这可能需要一点时间)qwq...

**Comment by HengXin666** [comment]
您好, 新的版本我已经修复了这个问题 (但是只有 **关闭** `二分爬取`的时候才有效果)

**Comment by zishu0802** [comment]
> 您好, 新的版本我已经修复了这个问题 (但是只有 **关闭** `二分爬取`的时候才有效果)

老大，关闭二分法就是从2009-01-1开始顺序爬取，这里的报错是这样的不过我没看出来怎么改
<img width="581" alt="image" src="https://github.com/user-attachments/assets/7cbb4c7b-7e91-415d-81ab-04a4ed928470">

**Comment by HengXin666** [comment]
您好, 请使用`最新版本`, 之前这里有点问题 (不会又遇到我没有测试到的问题了吧qwq)

`关闭二分法就是从2009-01-1开始顺序爬取`, 实际上, 您可以点击日期进行设置，从什么日期开始

**Comment by HengXin666** [comment]
> > 您好, 新的版本我已经修复了这个问题 (但是只有 **关闭** 二分爬取的时候才有效果)
> 
> 老大，关闭二分法就是从2009-01-1开始顺序爬取，这里的报错是这样的不过我没看出来怎么改 <img alt="图像" width="581" src="https://private-user-images.githubusercontent.com/185756502/386491574-7cbb4c7b-7e91-415d-81ab-04a4ed928470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTUxNzgsIm5iZiI6MTczMTY1NDg3OCwicGF0aCI6Ii8xODU3NTY1MDIvMzg2NDkxNTc0LTdjYmI0YzdiLTdlOTEtNDE1ZC04MWFiLTA0YTRlZDkyODQ3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzE0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWFmYWM4NjY5YzY5MmQ4NDQ5NzQwNDk1Y2Y1N2JiODAyZTFmNTkzZTQyMzhkMjg4MDBlODNkYTQ5ZTQzNTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2JvtpoFThOw9JA3UOPqTm70KTm2OmFkVGYb-e3aeZRk">

如果需要exe的话，需要等一下，我还在编译 (最新版本是`1.1.7`)

**Comment by zishu0802** [comment]
> 您好, 请使用`最新版本`, 之前这里有点问题 (不会又遇到我没有测试到的问题了吧qwq)
> 
> `关闭二分法就是从2009-01-1开始顺序爬取`, 实际上, 您可以点击日期进行设置，从什么日期开始

应该是因为我给你发那个bug，所以关闭二分法时设置的日期不管用，自动从2009开始读取

**Comment by HengXin666** [comment]
> 应该是因为我给你发那个bug，所以关闭二分法时设置的日期不管用，自动从2009开始读取


![PixPin_2024-11-15_15-25-13](https://github.com/user-attachments/assets/9c780e11-affb-4cf9-ad06-025467845ffb)

最新的1.1.7版本理论上已经修复了这个bug, 请确认是否升级了版本; 

另外如图, 您可以看看配置文件是否把起始日期显示为您的输入框的内容, (保险起见可以重启一下程序, 这样会读取一次配置文件到内存)

**Comment by HengXin666** [comment]
> > > 应该是因为我给你发那个bug，所以关闭二分法时设置的日期不管用，自动从2009开始读取
> > 
> > 
> > ![PixPin_2024-11-15_15-25-13](https://private-user-images.githubusercontent.com/103022267/386496469-9c780e11-affb-4cf9-ad06-025467845ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTU5NTYsIm5iZiI6MTczMTY1NTY1NiwicGF0aCI6Ii8xMDMwMjIyNjcvMzg2NDk2NDY5LTljNzgwZTExLWFmZmItNGNmOS1hZDA2LTAyNTQ2Nzg0NWZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjFmZjFmNjg5MmE5OTZkMjViZGUyZDJiNjljNzM5YTc1OGVlNWE3YzMyOGY2YWFhYzM0MzY5ZWI1ZjU5NzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L90bPIp6kGrXygjBUj1nrc2ZhNEax8yCByCECDpKaKs)
> > 最新的1.1.7版本理论上已经修复了这个bug, 请确认是否升级了版本;
> > 另外如图, 您可以看看配置文件是否把起始日期显示为您的输入框的内容, (保险起见可以重启一下程序, 这样会读取一次配置文件到内存)
> 
> 0.0原来我下载的不是最新版本...

最新的EXE版本在 https://github.com/HengXin666/BiLiBiLi_DanMu_Crawling/releases/tag/New-V1.1.7 , 我刚刚已经更新上去了, 您可以试一试, 我也不确定有没有我没有测试到bug...

> 有问题可以继续说嗷~
