### ISSUE TITLE
V1.1.7版本，开始时间的设置有bug

### ISSUE THREAD

**Issue by Waynehzw** [HengXin666/BiLiBiLi_DanMu_Crawling#6]
我是在windows电脑上使用的，设置好开始时间，点开始爬取，软件会沿用上一次的开始时间。
点停止爬取，删掉生成的xml文件，再点开始爬取，才会采用刚刚设置的开始时间。

另外，希望这个文件默认后缀是xml文件，改名字不用手动输入后缀.xml

**Comment by HengXin666** [comment]
感谢您的反馈, 我已经在`V1.1.8`版本修复这个问题, 我初步测试没有发现什么问题; 您可以试试, 如果有Bug可以继续提出来~
